version: '3.7'
services:
  seqgen:
    container_name: seqgen
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
     - ASPNETCORE_ENVIRONMENT=Development
     - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
     - ASPNETCORE_URLS=http://+:42501     
     - DOTNET_USE_POLLING_FILE_WATCHER=true
     - Logging__Console__FormatterName=Simple
    networks:
      - devnet
    ports:
      - "49728:42501"

networks:
  devnet:
    external: true    
